/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AgentRegistry {
      
    export type AgentStruct = {id: BigNumberish, role: string, name: string, agentWallet: AddressLike, endpoint: string, metadataURI: string, active: boolean}

    export type AgentStructOutput = [id: bigint, role: string, name: string, agentWallet: string, endpoint: string, metadataURI: string, active: boolean] & {id: bigint, role: string, name: string, agentWallet: string, endpoint: string, metadataURI: string, active: boolean }
  
    }

  export interface AgentRegistryInterface extends Interface {
    getFunction(nameOrSignature: "agentCount" | "getAgent" | "owner" | "registerAgent" | "renounceOwnership" | "transferOwnership" | "updateAgent"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentRegistered" | "AgentUpdated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'agentCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAgent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerAgent', values: [string, string, AddressLike, string, string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateAgent', values: [BigNumberish, string, string, AddressLike, string, string, boolean]): string;

    decodeFunctionResult(functionFragment: 'agentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateAgent', data: BytesLike): Result;
  }

  
    export namespace AgentRegisteredEvent {
      export type InputTuple = [id: BigNumberish, role: string, name: string, agentWallet: AddressLike, endpoint: string, metadataURI: string];
      export type OutputTuple = [id: bigint, role: string, name: string, agentWallet: string, endpoint: string, metadataURI: string];
      export interface OutputObject {id: bigint, role: string, name: string, agentWallet: string, endpoint: string, metadataURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentUpdatedEvent {
      export type InputTuple = [id: BigNumberish, role: string, name: string, agentWallet: AddressLike, endpoint: string, metadataURI: string, active: boolean];
      export type OutputTuple = [id: bigint, role: string, name: string, agentWallet: string, endpoint: string, metadataURI: string, active: boolean];
      export interface OutputObject {id: bigint, role: string, name: string, agentWallet: string, endpoint: string, metadataURI: string, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentRegistry;
    waitForDeployment(): Promise<this>;

    interface: AgentRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    agentCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAgent: TypedContractMethod<
      [id: BigNumberish, ],
      [AgentRegistry.AgentStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerAgent: TypedContractMethod<
      [role: string, name: string, agentWallet: AddressLike, endpoint: string, metadataURI: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateAgent: TypedContractMethod<
      [id: BigNumberish, role: string, name: string, agentWallet: AddressLike, endpoint: string, metadataURI: string, active: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'agentCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAgent'): TypedContractMethod<
      [id: BigNumberish, ],
      [AgentRegistry.AgentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerAgent'): TypedContractMethod<
      [role: string, name: string, agentWallet: AddressLike, endpoint: string, metadataURI: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateAgent'): TypedContractMethod<
      [id: BigNumberish, role: string, name: string, agentWallet: AddressLike, endpoint: string, metadataURI: string, active: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgentRegistered'): TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
getEvent(key: 'AgentUpdated'): TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'AgentRegistered(uint256,string,string,address,string,string)': TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
      AgentRegistered: TypedContractEvent<AgentRegisteredEvent.InputTuple, AgentRegisteredEvent.OutputTuple, AgentRegisteredEvent.OutputObject>;
    

      'AgentUpdated(uint256,string,string,address,string,string,bool)': TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
      AgentUpdated: TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }