/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RevenueVaultInterface extends Interface {
    getFunction(nameOrSignature: "distributeERC20" | "owner" | "renounceOwnership" | "transferOwnership" | "withdrawERC20" | "withdrawNative"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ERC20Distributed" | "ERC20Withdrawn" | "NativeReceived" | "NativeWithdrawn" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'distributeERC20', values: [AddressLike, AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawERC20', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawNative', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'distributeERC20', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawERC20', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawNative', data: BytesLike): Result;
  }

  
    export namespace ERC20DistributedEvent {
      export type InputTuple = [token: AddressLike, recipients: AddressLike[], amounts: BigNumberish[]];
      export type OutputTuple = [token: string, recipients: string[], amounts: bigint[]];
      export interface OutputObject {token: string, recipients: string[], amounts: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ERC20WithdrawnEvent {
      export type InputTuple = [token: AddressLike, to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [token: string, to: string, amount: bigint];
      export interface OutputObject {token: string, to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NativeReceivedEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, amount: bigint];
      export interface OutputObject {from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NativeWithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RevenueVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): RevenueVault;
    waitForDeployment(): Promise<this>;

    interface: RevenueVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    distributeERC20: TypedContractMethod<
      [token: AddressLike, recipients: AddressLike[], amounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawERC20: TypedContractMethod<
      [token: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawNative: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'distributeERC20'): TypedContractMethod<
      [token: AddressLike, recipients: AddressLike[], amounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawERC20'): TypedContractMethod<
      [token: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawNative'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ERC20Distributed'): TypedContractEvent<ERC20DistributedEvent.InputTuple, ERC20DistributedEvent.OutputTuple, ERC20DistributedEvent.OutputObject>;
getEvent(key: 'ERC20Withdrawn'): TypedContractEvent<ERC20WithdrawnEvent.InputTuple, ERC20WithdrawnEvent.OutputTuple, ERC20WithdrawnEvent.OutputObject>;
getEvent(key: 'NativeReceived'): TypedContractEvent<NativeReceivedEvent.InputTuple, NativeReceivedEvent.OutputTuple, NativeReceivedEvent.OutputObject>;
getEvent(key: 'NativeWithdrawn'): TypedContractEvent<NativeWithdrawnEvent.InputTuple, NativeWithdrawnEvent.OutputTuple, NativeWithdrawnEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'ERC20Distributed(address,address[],uint256[])': TypedContractEvent<ERC20DistributedEvent.InputTuple, ERC20DistributedEvent.OutputTuple, ERC20DistributedEvent.OutputObject>;
      ERC20Distributed: TypedContractEvent<ERC20DistributedEvent.InputTuple, ERC20DistributedEvent.OutputTuple, ERC20DistributedEvent.OutputObject>;
    

      'ERC20Withdrawn(address,address,uint256)': TypedContractEvent<ERC20WithdrawnEvent.InputTuple, ERC20WithdrawnEvent.OutputTuple, ERC20WithdrawnEvent.OutputObject>;
      ERC20Withdrawn: TypedContractEvent<ERC20WithdrawnEvent.InputTuple, ERC20WithdrawnEvent.OutputTuple, ERC20WithdrawnEvent.OutputObject>;
    

      'NativeReceived(address,uint256)': TypedContractEvent<NativeReceivedEvent.InputTuple, NativeReceivedEvent.OutputTuple, NativeReceivedEvent.OutputObject>;
      NativeReceived: TypedContractEvent<NativeReceivedEvent.InputTuple, NativeReceivedEvent.OutputTuple, NativeReceivedEvent.OutputObject>;
    

      'NativeWithdrawn(address,uint256)': TypedContractEvent<NativeWithdrawnEvent.InputTuple, NativeWithdrawnEvent.OutputTuple, NativeWithdrawnEvent.OutputObject>;
      NativeWithdrawn: TypedContractEvent<NativeWithdrawnEvent.InputTuple, NativeWithdrawnEvent.OutputTuple, NativeWithdrawnEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }